# Generated by Django 3.1 on 2021-04-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfcapp', '0002_auto_20210423_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='gellaryimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='transformation\\img')),
            ],
        ),
    ]
