# Generated by Django 3.1 on 2021-04-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hfcapp', '0003_gellaryimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gellaryimg',
        ),
    ]
