# Generated by Django 3.1 on 2021-04-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfcapp', '0005_transformationimg_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='gellaryimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gellary\\img')),
            ],
        ),
        migrations.RemoveField(
            model_name='transformationimg',
            name='Category',
        ),
    ]
