# Generated by Django 3.1 on 2021-04-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfcapp', '0006_auto_20210423_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultsimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='transformation\\img')),
            ],
        ),
        migrations.CreateModel(
            name='Rewardsimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gellary\\img')),
            ],
        ),
    ]
