# Generated by Django 3.1 on 2021-04-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfcapp', '0007_resultsimg_rewardsimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility1', models.CharField(max_length=200)),
                ('facility2', models.CharField(max_length=200)),
                ('facility3', models.CharField(max_length=200)),
                ('facility4', models.CharField(max_length=200)),
                ('facility5', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='resultsimg',
            name='image',
            field=models.ImageField(upload_to='result\\img'),
        ),
        migrations.AlterField(
            model_name='rewardsimg',
            name='image',
            field=models.ImageField(upload_to='reward\\img'),
        ),
    ]
