# Generated by Django 3.1 on 2021-04-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfcapp', '0008_auto_20210424_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='couplePrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packages',
            name='month',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packages',
            name='singlePrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='packages',
            name='facility3',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='packages',
            name='facility4',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='packages',
            name='facility5',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
