# Generated by Django 3.1 on 2021-04-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfcapp', '0009_auto_20210424_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='more_Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('singlePrice', models.IntegerField(default=0)),
                ('couplePrice', models.IntegerField(default=0)),
                ('facility1', models.CharField(max_length=200)),
                ('facility2', models.CharField(max_length=200)),
                ('facility3', models.CharField(default=0, max_length=200)),
                ('facility4', models.CharField(default=0, max_length=200)),
                ('facility5', models.CharField(default=0, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(default=0, max_length=100)),
                ('phone', models.IntegerField()),
                ('month', models.IntegerField()),
                ('singlePrice', models.IntegerField(default=0)),
                ('couplePrice', models.IntegerField(default=0)),
                ('checkbox1', models.BooleanField()),
                ('checkbox2', models.BooleanField()),
            ],
        ),
    ]
