# Generated by Django 3.1 on 2021-04-26 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hfcapp', '0010_more_packages_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='checkbox1',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='checkbox2',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='couplePrice',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='month',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='singlePrice',
        ),
    ]
