# Generated by Django 3.1 on 2021-04-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfcapp', '0011_auto_20210426_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='more_packages',
            name='package_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='packages',
            name='package_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
