# Generated by Django 3.1 on 2021-04-26 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hfcapp', '0012_auto_20210426_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='more_packages',
            name='package_name',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='package_name',
        ),
    ]
