# Generated by Django 3.1 on 2021-04-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hfcapp', '0013_auto_20210426_1202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='more_Packages',
        ),
    ]
