# Generated by Django 3.1 on 2021-04-26 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hfcapp', '0014_delete_more_packages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Packages',
            new_name='Packagesa',
        ),
    ]
