# Generated by Django 3.1 on 2021-04-26 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hfcapp', '0015_auto_20210426_1546'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Packagesa',
            new_name='Packages',
        ),
    ]
