# Generated by Django 3.1 on 2021-04-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfcapp', '0016_auto_20210426_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='morePackages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('singlePrice', models.IntegerField(default=0)),
                ('couplePrice', models.IntegerField(default=0)),
                ('facility1', models.CharField(max_length=200)),
                ('facility2', models.CharField(max_length=200)),
                ('facility3', models.CharField(default=0, max_length=200)),
                ('facility4', models.CharField(default=0, max_length=200)),
                ('facility5', models.CharField(default=0, max_length=200)),
            ],
        ),
    ]
