# Generated by Django 3.1 on 2021-04-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfcapp', '0018_auto_20210426_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='morepackages',
            name='packagetitile',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
