# Generated by Django 3.1 on 2021-04-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfcapp', '0019_morepackages_packagetitile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morepackages',
            name='month',
        ),
        migrations.AddField(
            model_name='morepackages',
            name='days',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
